version: '3.3'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - thesis_db_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -p ${DATABASE_PORT}


  web:
    image: thesis_track
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thesis_track_backend
    # command: python manage.py runserver ${LOCAL_IP}:${SERVER_PORT}
    ports:
      - "${WEB_PORT_HOST}:${SERVER_PORT}"
    tty: true
    volumes:
      - .:/app:Z
      - ./media:/app/media
    environment:
      - DEBUG=${DEBUG}
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - DATABASE_HOST=${DATABASE_HOST}
      - GPT_API_KEY=${GPT_API_KEY}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - OLLAMA_URL=http://127.0.0.1:11434  # 👈 Usa directamente el puerto interno real de Ollama
    depends_on:
      - postgres
      - elasticsearch


  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: thesis_track_nginx
    ports:
      - "${SERVER_PORT2}:${SERVER_PORT}"
    depends_on:
      - postgres
      - web
      - elasticsearch
    volumes:
      - ./media:/app/media


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data


volumes:
  thesis_db_data:
  esdata:
