server {
    listen 80;
    server_name localhost;
    client_max_body_size 50M;  # Para manejar archivos grandes

    # Proxy principal: Django backend
    location / {
        proxy_pass http://thesis_track_backend:80;  # Aseguramos que use la variable correcta
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Admin de Django
    location /admin/ {
        proxy_pass http://thesis_track_backend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Servir archivos estáticos y media
    location /media/ {
        alias /app/media/;
        autoindex on;
    }
}
